#pragma once

#define IDI_CLIPSOUL_APP 1

#define IDR_CLIPSOUL_ICON_PIN 101
#define IDR_CLIPSOUL_ICON_PIN_ACTIVE 102
#define IDR_CLIPSOUL_ICON_CLOSE 103
#define IDR_CLIPSOUL_ICON_FILTER 104
#define IDR_CLIPSOUL_ICON_FILTER_ACTIVE 105
#define IDR_CLIPSOUL_ICON_MULTI_SELECT 106
#define IDR_CLIPSOUL_ICON_MULTI_SELECT_ACTIVE 107
#define IDR_CLIPSOUL_ICON_TRASH 108
#define IDR_CLIPSOUL_ICON_TEXT_KIND 109
#define IDR_CLIPSOUL_ICON_LINK_KIND 110
#define IDR_CLIPSOUL_ICON_ADD_FAVORITE_FOLDER_OUTLINE 111
#define IDR_CLIPSOUL_ICON_ADD_FAVORITE_FOLDER_FILLED 112
